Make Connector more testable
damm1t/android-set pull request #4
Opened 2020-12-12 20:01 UTC by RSBat

Socket and LocalBroadcastManager are now constructor params and allow mocking

2020-12-12 21:13 UTC, RSBat commented
Оно крешится :cry:

2020-12-12 21:14 UTC, merak1t approved these changes

2020-12-12 21:20 UTC, merak1t requested changes
set up server

2020-12-14 16:04 UTC, merak1t approved these changes

2020-12-14 16:11 UTC, merged